### ISSUE TITLE
Any example

### ISSUE THREAD

**Issue by suhail-ansari-apconic** [mrphu3074/meteor-react-bootstrap#1]
I have been trying to use it with Meteor 1.2.0.2 and the button shows as a normal button.

ReactBootstrap.Button bsStyle="primary" bsSize="large">Large button</ReactBootstrap.Button

**Comment by mrphu3074** [comment]
@suhail-ansari-apconic  sorry about my bad document. You need to add bootstrap css into your project. 
[React bootstrap - Getting started](https://react-bootstrap.github.io/getting-started.html) 

Or you can use `twbs:bootstrap` , it's better.

**Comment by suhail-ansari-apconic** [comment]
That worked thanks.
